### ISSUE TITLE
五笔反查里面会有符号候选 zz开头的符号字符 不知道是什么原因

### ISSUE THREAD

**Issue by vision976899957** [rime/rime-wubi#10]
https://tieba.baidu.com/p/2497660964?red_tag=3564745168 和这个情况类似 但是我的/bd是正常的 反查是z 就会出现帖子中的情况 感谢解答

**Comment by lotem** [comment]
碼表裏有這些字符

**Comment by vision976899957** [comment]
感谢回答！
