### ISSUE TITLE
163 characters from 「通用规范汉字表」 are not included in `wubi86.dict.yaml`

### ISSUE THREAD

**Issue by rdrg109** [rime/rime-wubi#15]
I wrote a Python script for finding the characters defined in 「通用规范汉字表」, but that are not included in `wubi86.dict.yaml`. I noticed that there's a total of 163 character that are not included in `wubi86.dict.yaml`. The Python script is shown below. The file `8105.txt` contains the 8105 characters in 「通用规范汉字表」 and it was downloaded from [this repository](https://github.com/zhmars/rime-wubi-simp/blob/master/data/8105.txt) [(permalink to version as of the time of this writing)](https://github.com/zhmars/rime-wubi-simp/blob/c407b9fcf2e9c2fa2d9a0c2581a48920463ca9b3/data/8105.txt)

```
$ cat main.py
```
```python
import  re

filename_8105 = '8105.txt'
filename_dict = 'wubi86.dict.yaml'

set_8105 = set()
set_dictionary = set()

with open(filename_8105) as f:
    for line in f:
        results = re.search(r"^[0-9]+ (.)", line)
        set_8105.add(results.group(1))

with open(filename_dict) as f:
    for line in f:
        if line == '---\n':
            break
    for line in f:
        if results := re.search(r"^(.)	", line):
            set_dictionary.add(results.group(1))

diff = set_8105.difference(set_dictionary)
print(len(diff))
print(''.join(diff))
```

```
$ python main.py
```
```
163
𬒈𫸩𫖯𬬮𫄨𫓶𬺈𬣳𬍤𪩘𫘦𫶇𫟼𬸦𬣞𬭼𬘘𪾢𪨶𬭩𬒗𫟹𬇙𫟅𬙋𪨰𫰛𫘧𫮃𬸘𪟝鿍𬴃𬱟𬭛𫭼𫷷𬶟𬘫𬤇𬬩𫞩𬮿𬶠𪤗𬕂𬨂𬭬𬊤𬒔𫇭𫭟𬯀𫠊𫘪𬟁𬬸𫔎𬘩𬤊𫚖𬶋𬘓𬇹𫌀𫄷𫘬鿏𬃊𬳵𬴂𫍯𪣻𫍣𬺓𫔍𫠆𬬿𫓧𬮱𬇕𫗧𫚭𬀩𬍛𬸪𫫇𫑡𬭤𬘡𬶏𬸣𬉼𬭁𫢸𫔶𬞟𫐐𬬻𫘜𬬭𬶭𬸚𫐄𬭊𬶮𬳿𬹼𬬹𫍽𬜯𫟦𫐓𬪩𬌗𫓹𬙊𫛭𫍲𬷕𫚕𬳶𬩽𬀪𬭶𬭯𬊈𬘬𫘝𫭢𬴊𬍡𬟽𬘭𬤝𬭳𫘨𬳽鿎𬶍𬱖𬭸𬜬𫗴𫓯𫄸𬘯𫵷𬙂𬬱𬶨𫄧𬂩𬶐𫖮𬣡𬨎𫖳𬯎𬭚𬭎𫠜𬣙
```

Why aren't these characters included in `wubi86.dict.yaml`? I'm asking because I could open a pull request for including these characters along with their Wubi 86 codes.

**Comment by lotem** [comment]
The data originate from the ibus-table project.
Those characters aren't included because the project dates before the standard 通用规范汉字表.

**Comment by rdrg109** [comment]
@lotem Thanks for the response. Is there something that avoid those characters to be added? If there isn't, I could open a pull request to include those characters along with their Wubi86 codes.

**Comment by lotem** [comment]
Sure. Pull requests are welcome.

**Comment by rdrg109** [comment]
Here's the code of the characters that are not included. I'll proceed to open a pull request.

```
𬳶	cmkg
𬀩	jfnh
𫄷	xujn
𬉼	oaqy
𫞩	gagw
𬇹	ilgy
𬨎	lusg
𫓶	qkeg
𬒈	ipdf
𫑡	kjnb
𫍲	yvhc
𬭶	qlfo
𬘯	xybg
𬍛	gqiy
𬴂	cdjd
𫠜	hwbq
𬘓	xkh
𬭛	qihc
𬭸	qoqh
𬺓	hwbh
𫚕	qgjh
𬬻	qhnt
𬮿	bmnn
𫘧	cviy
𪨶	mdlj
𬺈	hwbk
𬴊	coqh
𬳽	ctfq
𬷕	gehg
𫔎	qcbk
𬣡	ygt
𫗴	qnyg
𬍡	inry
𬶮	qgfk
𬶭	qgwi
𬤊	yjgh
𬘘	xpqn
𬤇	ysfg
𬞟	ahim
𬶨	vcag
𫘪	cdri
𬂩	sguw
𫄨	xqdh
𬭁	qxgu
𫠊	cyxy
𪾢	hmqn
𬒔	dheg
𫚭	qgvn
𬘡	xldy
𬙂	xpgw
𬩽	vfbh
𬭼	quep
𬶍	qgpx
𬱟	qdbm
𫐄	lgqn
𫍯	ydgt
𬟽	jaiy
𫄸	xtgo
鿏	qgty
𫐓	lcbs
𫍣	ymgk
𬬿	qvkg
𬜯	agmw
𫌀	pugm
𫄧	xthp
𬬮	qtay
𬸦	yttg
𫖳	vtkm
𬒗	djtq
𫭟	faqy
𫖮	mndm
𬳿	cwty
𬮱	usfd
𫘦	cqrm
𪤗	fnwe
𬬩	qay
𬍤	gvfy
𬙋	xyke
𪣻	fovg
𬶏	qgdb
𫢸	wujf
鿍	ftah
𫘬	cexd
𫵷	mdln
𬸣	pfjg
𬘬	xgeg
𬬸	qsyy
𫖯	iqdm
𫍽	ylge
𫟅	xyiy
𬳵	cgig
𬘭	xssy
𫟼	qdpy
𬪩	sgpe
𬭎	qpdc
𬤝	ygjn
𫇭	ayly
𬊈	ovfy
𬶟	qggj
鿎	ddpy
𬙊	xlff
𬣞	ypgg
𬭳	qfkk
𫟹	qawy
𫓹	qadw
𫗧	qngi
𫭢	fwxn
𬶠	qggi
𬣙	ygfh
𬹼	hwbj
𬇕	idnn
𫓧	qfwy
𬕂	tamu
𬘩	xtfp
𬭩	qwcn
𬟁	agkg
𬸪	tolg
𬬱	qrh
𬬭	qwxn
𫫇	kgon
𪨰	mmag
𬱖	mdmy
𫛭	qtgg
𫔶	uths
𫐐	lvqn
𬌗	ahtk
𪟝	gmln
𬭬	qdhv
𬇙	imy
𫸩	xaqy
𫮃	fujf
𬯎	bkhm
𬃊	srfm
𬸚	qtyg
𫶇	mgkh
𬬹	qjhh
𬜬	aukf
𫟦	luep
𫘨	cjgh
𬘫	xpfq
𬨂	lqan
𬸘	ajvg
𬶋	qgqk
𫚖	hxqg
𬭯	qumt
𬣳	yvey
𫭼	fapl
𫰛	vcag
𬊤	oujf
𬭚	qybg
𫠆	fcdm
𪩘	mfmd
𬴃	cdhk
𬯀	byjh
𬭤	qwnd
𫘜	cyy
𫷷	yqqw
𬶐	qgiq
𫓯	qffg
𫘝	cnwy
𬭊	qsfg
𬀪	jmqn
𫔍	qtol
```

**Comment by rdrg109** [comment]
> Sure. Pull requests are welcome.

@lotem I've opened a pull request. Please see #20

**Comment by lotem** [comment]
Merged. Thanks.
