### ISSUE TITLE
是否可以扩增一下《现代汉语词典》？

### ISSUE THREAD

**Issue by yveshield** [rime/rime-wubi#22]
第7版大约7万词，都是标准的、成熟的词语，而非杂乱的网络用语，可以考虑一下收录进来

https://zh.wikipedia.org/wiki/%E7%8E%B0%E4%BB%A3%E6%B1%89%E8%AF%AD%E8%AF%8D%E5%85%B8

https://github.com/CNMan/XDHYCD7th

**Comment by lotem** [comment]
我建議你另建一個項目，準備一個單獨的詞典文件，需要時通過詞典引用的方式加進來。

五筆詞庫並不是越大越好。有的用戶喜歡大詞庫；有的用戶喜歡精簡詞庫，優點是重碼較少。
由於五筆字詞混合編碼的特點，增加這麼多詞，必然提高重碼率，很多以往沒有重碼的字詞無法自動上屏，這會干擾已有用戶輸入。
