### ISSUE TITLE
怎么用z键输入符号？

### ISSUE THREAD

**Issue by ernsky** [rime/rime-wubi#4]
在0.13.0之前还是可以的，升级后不行了，怎么回事？

**Comment by ernsky** [comment]
自己的几个设置，共享下：

1. 候选栏由垂直变横排：
打开用户文件夹中build文件夹的weasel.yaml文件，在最后面的style:中，修改以下代码：
    font_point: 20
    horizontal: true
    inline_preedit: true

2. 分号与引号选字
打开用户文件夹中build文件夹的wubi86.schema.yaml文件，在key_binder:/bindings:的最后两行添加

    - { when: has_menu, accept: semicolon, send: 2 }
    - { when: has_menu, accept: apostrophe, send: 3 }
    
3. 符号输入：
打开用户文件夹中build文件夹的wubi86.schema.yaml文件，在  recognizer:/patterns后加入，
    punct: "^/([a-z]+|[0-9]0?)$"

**Comment by lotem** [comment]
`z`鍵配置爲拼音反查。
