### ISSUE TITLE
0.14.0安装以后无法使用，重度五笔拼音混合输入法用户

### ISSUE THREAD

**Issue by marco9989** [rime/rime-wubi#7]
0.14.0安装以后无法使用，重度五笔拼音混合输入法用户

**Comment by lotem** [comment]
這個軟件只包含數據，沒有版本號。
題中的 `0.14.0` 是什麼軟件？
五筆是怎麼安裝的？

**Comment by marco9989** [comment]
那是鼠须管主程序，在rime.im上下载的

发自我的 iPhone

**Comment by lotem** [comment]
這條信息很關鍵，因爲在不同系統上發佈了不同的產品，只提供版本號是有歧義的。
鼠鬚管主程序，顧名思義就是輸入法程序而已。不包含你所使用的那款輸入法的數據文件。
如果預設的拼音輸入法可以使用，可能是數據缺失。參考： https://github.com/rime/squirrel/issues/279

**Comment by marco9989** [comment]
我意思是我原来使用的Mac版的鼠须管0.9.26版本，部署的是五笔拼音输入法，升级到0.14.0以后原来部署的东西就失效了，显示部署错误，必须重新搞方案。

在 2019年7月1日，19:52，弓辰 <notifications@github.com<mailto:notifications@github.com>> 写道：


這條信息很關鍵，因爲在不同系統上發佈了不同的產品，只提供版本號是有歧義的。
鼠鬚管主程序，顧名思義就是輸入法程序而已。不包含你所使用的那款輸入法的數據文件。
如果預設的拼音輸入法可以使用，可能是數據缺失。參考： rime/squirrel#279<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frime%2Fsquirrel%2Fissues%2F279&data=02%7C01%7C%7Ca6d2ba1246dd48e6b06208d6fe1a8958%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636975787254705370&sdata=T3BonixjStKoHboG%2FdTHVEG%2FO%2FDij6RExhfv0ApsBWY%3D&reserved=0>

**Comment by lotem** [comment]
你说得对。部署生成的数据文件不保证版本兼容。重新生成需要YAML源文件。
输入法安装程序不包含五笔输入方案的源文件。

**Comment by caogee** [comment]
小狼毫
https://blog.csdn.net/chokee/article/details/120337253
小狼毫0.14 五笔拼音混输 Rime14
小狼毫0.14 五笔拼音混输 Rime14

RIME小狼毫0.14 五笔拼音配置，好的东西应该传播
下载后直接覆盖目录就好，做好备份原目录
https://download.csdn.net/download/chokee/23283170
