### ISSUE TITLE
问题：如何配置只输出简体中文同时保证输出结果正确

### ISSUE THREAD

**Issue by zhmars** [rime/rime-wubi#8]
根据  [pull request\#3](https://github.com/rime/rime-wubi/pull/3) 提出的问题

当前词库输入 `utem`，会出现两个候选`顔  颜`，配置 `simplification` 选项可以只输出简体字 `颜`，但配置后如果输入 `tvfh`，会出现候选`笔  律`，`笔` 的五笔全码是 `ttfn`，本不应该出现在这里。

请问，当前词库怎样配置才能如何保证以下结果
- `utem` 不会出现繁体字 `顔`
-  `tvfh` 不会出现错误编码字 `笔`

**Comment by zhmars** [comment]
目前的解决方案还是简繁体词库分开，我基于现在的词库和现行标准《通用规范汉字表》生成一份简体词库，放在 [zhmars/rime-wubi-simp](https://github.com/zhmars/rime-wubi-simp) ，有需要的可以试试 :)

**Comment by chenzhiwei** [comment]
我自己也单独维护了一份五笔和拼音词库，目前的五笔太乱了，很多没必要存在的繁体字。https://github.com/chenzhiwei/rime
